
package Forms;

import Smart_Student_Backend.AddSubjectInfoBackEnd;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class AddSubjectInfo extends javax.swing.JFrame {

   
    public AddSubjectInfo() {
        initComponents();
        setIconandLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        SubCodeTF = new javax.swing.JTextField();
        TeacherTF = new javax.swing.JTextField();
        SubNameTF = new javax.swing.JTextField();
        DurationTF = new javax.swing.JTextField();
        CreditTF = new javax.swing.JTextField();
        TeacherEmailTF = new javax.swing.JTextField();
        TeacherPhoneTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubCodeTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(SubCodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 180, -1));

        TeacherTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(TeacherTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 180, -1));

        SubNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(SubNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 180, -1));
        jPanel3.add(DurationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 70, -1));
        jPanel3.add(CreditTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 60, 20));

        TeacherEmailTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(TeacherEmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 180, -1));

        TeacherPhoneTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(TeacherPhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 180, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 160, 100));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add  Subject  information");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 430, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Credit :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Duration :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Teacher Name  :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Subject Name :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Teacher Mail :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Teacher Phone :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Subject Code :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        BackBtn.setBackground(new java.awt.Color(225, 190, 88));
        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel3.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        SaveBtn.setBackground(new java.awt.Color(225, 190, 88));
        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveBtn.setText("Save information");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel3.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/addroutine.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        jLabel10.setBackground(new java.awt.Color(103, 65, 114));
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(225, 190, 88));
        jLabel10.setText("Add  Subject  information");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 980, 580));

        setSize(new java.awt.Dimension(983, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        boolean input=false;
        String CourseCode = SubCodeTF.getText();
        String CourseName = SubNameTF.getText();
        String TeacherName= TeacherTF.getText();
        
        String TeacherPhone=TeacherPhoneTF.getText();
        String TeacherEmail=TeacherEmailTF.getText();
        if(TeacherEmail.isEmpty()){
            TeacherEmail="NA";
        }
        if(TeacherPhone.isEmpty()){
            TeacherPhone="NA";
        }
        int CourseCredit=0;
        double ClassDuration=0;
        try {
            CourseCredit=Integer.parseInt(CreditTF.getText());
            ClassDuration=Double.parseDouble(DurationTF.getText());
            input=true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Try Integer Number");
        }
 
        
        
        
        if(input==true){
         AddSubjectInfoBackEnd AddSubject = new AddSubjectInfoBackEnd();
        AddSubject.setValue(CourseCode, CourseName, TeacherName, TeacherPhone, TeacherEmail,CourseCredit, ClassDuration);
        boolean Existance=AddSubject.CheckExistance();
        if(Existance==true){
            JOptionPane.showMessageDialog(null,CourseCode+", Is Already in your list");
        }else{
            boolean success=AddSubject.saveinfo();
            if(success==true){
                JOptionPane.showMessageDialog(null, "Information Saved");
            resetField();
            }
        }   
        }
         
        
        
        
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void resetField(){
        SubCodeTF.setText(null);
        SubNameTF.setText(null);
        TeacherEmailTF.setText(null);
        TeacherPhoneTF.setText(null);
        TeacherTF.setText(null);
        CreditTF.setText(null);
        DurationTF.setText(null);
    }
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
       new addclass().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSubjectInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSubjectInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSubjectInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubjectInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSubjectInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField CreditTF;
    private javax.swing.JTextField DurationTF;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField SubCodeTF;
    private javax.swing.JTextField SubNameTF;
    private javax.swing.JTextField TeacherEmailTF;
    private javax.swing.JTextField TeacherPhoneTF;
    private javax.swing.JTextField TeacherTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
