
package Forms;

import Forms.home_page;
import Smart_Student_Backend.DeleteReminderBackEnd;
import Smart_Student_Backend.EditReminderBackEnd;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class delete_reminder_info extends javax.swing.JFrame {
    String Date;
    String Time;
    String CourseCode;
    String Title;
    String Discription;
   
    public delete_reminder_info() {
        initComponents();
        setIconandLocation();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DeleteBtn = new javax.swing.JButton();
        YearCMBox = new javax.swing.JComboBox<>();
        MonthCMBox = new javax.swing.JComboBox<>();
        DayCMBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        MeridiemCMBox = new javax.swing.JComboBox<>();
        MinuteCMBox = new javax.swing.JComboBox<>();
        HourCMBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 100));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel6.setText("Edit Reminder");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(103, 65, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteBtn.setBackground(new java.awt.Color(232, 126, 4));
        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        YearCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        YearCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jPanel2.add(YearCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        MonthCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MonthCMBox.setMaximumRowCount(12);
        MonthCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan ", "Feb ", "Mar", "Apr ", "May", "Jun ", "Jul ", "Aug", "Sep", "Oct", "Nov", "Dec " }));
        MonthCMBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthCMBoxActionPerformed(evt);
            }
        });
        jPanel2.add(MonthCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        DayCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DayCMBox.setMaximumRowCount(12);
        DayCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31 " }));
        jPanel2.add(DayCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select Date  :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        MeridiemCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MeridiemCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A.M", "P.M" }));
        jPanel2.add(MeridiemCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        MinuteCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MinuteCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jPanel2.add(MinuteCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, -1));

        HourCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HourCMBox.setMaximumRowCount(12);
        HourCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(HourCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Time  :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 680, 360));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 760, 500));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar124.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 960, 590));

        setSize(new java.awt.Dimension(956, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void MonthCMBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthCMBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthCMBoxActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed

        String Day=DayCMBox.getItemAt(DayCMBox.getSelectedIndex());
        String Month=MonthCMBox.getItemAt(MonthCMBox.getSelectedIndex());
        String Year=YearCMBox.getItemAt(YearCMBox.getSelectedIndex());
        Date=Day+"-"+Month+"-"+Year;
        String Minute=MinuteCMBox.getItemAt(MinuteCMBox.getSelectedIndex());
        String Hour=HourCMBox.getItemAt(HourCMBox.getSelectedIndex());
        String Meridiem=MeridiemCMBox.getItemAt(MeridiemCMBox.getSelectedIndex());
        int temp=Integer.parseInt(Hour);
        if(Meridiem.equals("P.M")){
            if(temp!=12){
                int temp2=temp+12;
                Hour=String.valueOf(temp2);
            }   
        }else{
            if(temp==12){
               JOptionPane.showMessageDialog(rootPane, "There is no such This as 12:..:AM");
            }
        }
        Time=Hour+":"+Minute;
        DeleteReminderBackEnd deletereminder= new DeleteReminderBackEnd (CourseCode,Date,Time);
        boolean check=deletereminder.getInfoFromDataBase();
        if(check==true){
            this.CourseCode=deletereminder.CourseCode;
            this.Title=deletereminder.Title;
            this.Discription=deletereminder.Discription;
            boolean Confirm=Confirm();
            if(Confirm==true){
                boolean success=false;//=deletereminder.delete();
                if(success==true){
                    JOptionPane.showMessageDialog(rootPane, "Information Deleted");
                }
            }
        }else{
            System.out.println(check);
            JOptionPane.showMessageDialog(rootPane, "Date:"+Date+"\nTime"+Time+"\nData Not Exist");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private boolean Confirm(){
        boolean confirm=false;
        int select = JOptionPane.showConfirmDialog(null, "Subject:"+CourseCode+"\nDate and Time:"+Date+" at "+Time+"\nTitle"+Title+"\nDiscription:"+Discription, "Confirm",
        JOptionPane.YES_NO_OPTION);
        if(select==0){
            confirm=true;
        }
        return confirm;
    }
    
    
    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
       new home_page().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_reminder_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_reminder_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_reminder_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_reminder_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_reminder_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JComboBox<String> DayCMBox;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JComboBox<String> HourCMBox;
    private javax.swing.JComboBox<String> MeridiemCMBox;
    private javax.swing.JComboBox<String> MinuteCMBox;
    private javax.swing.JComboBox<String> MonthCMBox;
    private javax.swing.JComboBox<String> YearCMBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
