
package Forms;

import Smart_Student_Backend.EditSubjectInfoBackEnd;
import Smart_Student_Backend.ViewSubjectInfoBackEnd;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class edit_subject_info extends javax.swing.JFrame {
    private String CourseCode;
 
    
    public edit_subject_info() {
        initComponents();
    }
    
    public edit_subject_info(String CourseCode) {
        initComponents();
        this.CourseCode=CourseCode;
        setInfo();
        setIconandLocation();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CourseCodeTF = new javax.swing.JTextField();
        TeacherName = new javax.swing.JTextField();
        CourseNameTF = new javax.swing.JTextField();
        ClassDurationTF = new javax.swing.JTextField();
        CourseCreditTF = new javax.swing.JTextField();
        TeacherMailTF = new javax.swing.JTextField();
        TeacherPhoneTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        UpdateInfoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CourseCodeTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(CourseCodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 180, -1));

        TeacherName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(TeacherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 180, -1));

        CourseNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(CourseNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 180, -1));
        getContentPane().add(ClassDurationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 70, -1));

        CourseCreditTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseCreditTFActionPerformed(evt);
            }
        });
        getContentPane().add(CourseCreditTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 60, 20));

        TeacherMailTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(TeacherMailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 180, -1));

        TeacherPhoneTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(TeacherPhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 180, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 160, 100));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edit Subject information");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 380, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cradit :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Duration :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Teacher Name  :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Subject Name :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Teacher Mail :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Teacher Phone :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Subject Code :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jButton3.setBackground(new java.awt.Color(225, 190, 88));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        UpdateInfoBtn.setBackground(new java.awt.Color(225, 190, 88));
        UpdateInfoBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateInfoBtn.setText("Update information");
        UpdateInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/addroutine.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 580));

        setSize(new java.awt.Dimension(956, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    
    public void setInfo(){
        ViewSubjectInfoBackEnd viewsubject = new ViewSubjectInfoBackEnd(CourseCode);
        viewsubject.getInfoFromDataBase();
        CourseCodeTF.setText(CourseCode);
        CourseNameTF.setText(viewsubject.CourseName);
        CourseCreditTF.setText(String.valueOf(viewsubject.CourseCredit));
        TeacherName.setText(viewsubject.CourseTeacher);
        TeacherMailTF.setText(viewsubject.TeacherEmail);
        TeacherPhoneTF.setText(viewsubject.TecherPhone);
        ClassDurationTF.setText(String.valueOf(viewsubject.Duration));
        
    }
    private void CourseCreditTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseCreditTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseCreditTFActionPerformed

    private void UpdateInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoBtnActionPerformed
        CourseCode=CourseCodeTF.getText();
        String CourseName=CourseNameTF.getText();
        int CourseCredit=Integer.parseInt(CourseCreditTF.getText());
        String CourseTeacher=TeacherName.getText();
        String TeacherMail=TeacherMailTF.getText();
        String TeacherPhone=TeacherPhoneTF.getText();
        double ClassDuration=Double.parseDouble(ClassDurationTF.getText()) ;
        EditSubjectInfoBackEnd editsubject = new EditSubjectInfoBackEnd();
        editsubject.setValue(CourseCode, CourseName, CourseCredit, CourseTeacher, TeacherMail, TeacherPhone, ClassDuration);
        boolean Success=editsubject.updateInfo();
        if(Success==true){
            JOptionPane.showMessageDialog(rootPane,"Information Updated");
            new EditClass().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "No Information Updated");
        }
    }//GEN-LAST:event_UpdateInfoBtnActionPerformed

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new EditClass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_subject_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClassDurationTF;
    private javax.swing.JTextField CourseCodeTF;
    private javax.swing.JTextField CourseCreditTF;
    private javax.swing.JTextField CourseNameTF;
    private javax.swing.JTextField TeacherMailTF;
    private javax.swing.JTextField TeacherName;
    private javax.swing.JTextField TeacherPhoneTF;
    private javax.swing.JButton UpdateInfoBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
