
package Forms;

import Forms.home_page;
import Smart_Student_Backend.DBConnect;
import Smart_Student_Backend.DeleteSubjectInfoBackEnd;
import Smart_Student_Backend.Temp;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class EditClass extends javax.swing.JFrame {
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;

   
    public EditClass() {
        initComponents();
        setsubject();
        setIconandLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EditSubjectInfoBtn = new javax.swing.JButton();
        EditRoutine = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SubjectCMBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, -1, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 100));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel6.setText("Edit");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(78, 205, 196));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditSubjectInfoBtn.setBackground(new java.awt.Color(52, 73, 94));
        EditSubjectInfoBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditSubjectInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditSubjectInfoBtn.setText("    Edit  Subject Information");
        EditSubjectInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSubjectInfoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(EditSubjectInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, 60));

        EditRoutine.setBackground(new java.awt.Color(52, 73, 94));
        EditRoutine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditRoutine.setForeground(new java.awt.Color(255, 255, 255));
        EditRoutine.setText("     Edit Routine Information");
        EditRoutine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditRoutineActionPerformed(evt);
            }
        });
        jPanel2.add(EditRoutine, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 60));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, -1));

        SubjectCMBox.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jPanel2.add(SubjectCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 140, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject Code :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 650, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 690, 420));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/barckground.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 580));

        setSize(new java.awt.Dimension(986, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void EditSubjectInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSubjectInfoBtnActionPerformed
       String CourseCode=SubjectCMBox.getItemAt(SubjectCMBox.getSelectedIndex());
       new edit_subject_info(CourseCode).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_EditSubjectInfoBtnActionPerformed

    private void EditRoutineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRoutineActionPerformed
        String CourseCode=SubjectCMBox.getItemAt(SubjectCMBox.getSelectedIndex());
        new routineedit(CourseCode).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditRoutineActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
      new home_page().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    
    
    public void setsubject(){
        con=new DBConnect().connectDB();
       String User = new Temp().getUser();
        String sql = "Select * from S_SubjectInfo where Email=?" ;
            try{
                pst=con.prepareStatement(sql);
                pst.setString(1,User);
                rs = pst.executeQuery();
                while(rs.next()){
                String Subject = rs.getString("S_Code");
                 SubjectCMBox.addItem(Subject);
                }
            }catch (Exception ex){
                
            }
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JButton EditRoutine;
    private javax.swing.JButton EditSubjectInfoBtn;
    private javax.swing.JComboBox<String> SubjectCMBox;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
