
package Forms;

import Smart_Student_Backend.DBConnect;
import Smart_Student_Backend.EditReminderBackEnd;
import Smart_Student_Backend.Temp;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class edit_reminder extends javax.swing.JFrame {
    EditReminderBackEnd editreminder;
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
 
    public edit_reminder() {
        initComponents();
    }
    public edit_reminder(EditReminderBackEnd object) {
        initComponents();
        editreminder=object;
        
        setInfo();
        setIconandLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        YearCMBox = new javax.swing.JComboBox<>();
        MonthCMBox = new javax.swing.JComboBox<>();
        DayCMBox = new javax.swing.JComboBox<>();
        MeridiemCMBox = new javax.swing.JComboBox<>();
        MinuteCMBox = new javax.swing.JComboBox<>();
        HourCMBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CourseCodeCMBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TitleTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DiscriptionTA = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 100));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Task Related Subject :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 230, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel6.setText("Edit Reminder");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(103, 65, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveBtn.setBackground(new java.awt.Color(232, 126, 4));
        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        YearCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        YearCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jPanel2.add(YearCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        MonthCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MonthCMBox.setMaximumRowCount(12);
        MonthCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan ", "Feb ", "Mar", "Apr ", "May", "Jun ", "Jul ", "Aug", "Sep", "Oct", "Nov", "Dec " }));
        MonthCMBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthCMBoxActionPerformed(evt);
            }
        });
        jPanel2.add(MonthCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        DayCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DayCMBox.setMaximumRowCount(12);
        DayCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31 " }));
        jPanel2.add(DayCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        MeridiemCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MeridiemCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A.M", "P.M" }));
        jPanel2.add(MeridiemCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        MinuteCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MinuteCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jPanel2.add(MinuteCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 70, -1));

        HourCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HourCMBox.setMaximumRowCount(12);
        HourCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel2.add(HourCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Time  :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        CourseCodeCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(CourseCodeCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 130, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Discription :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 130, -1));

        TitleTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(TitleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 220, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Title  :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 70, -1));

        DiscriptionTA.setColumns(20);
        DiscriptionTA.setRows(5);
        jScrollPane1.setViewportView(DiscriptionTA);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 340, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Date  :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Select Date  :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 680, 360));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 760, 500));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar124.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 970, 580));

        setSize(new java.awt.Dimension(970, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void MonthCMBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthCMBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthCMBoxActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new reminderedit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        String CourseCode=CourseCodeCMBox.getItemAt(CourseCodeCMBox.getSelectedIndex());
        String Day=DayCMBox.getItemAt(DayCMBox.getSelectedIndex());
        String Month=MonthCMBox.getItemAt(MonthCMBox.getSelectedIndex());
        String Year=YearCMBox.getItemAt(YearCMBox.getSelectedIndex());
        String Date=Day+"-"+Month+"-"+Year;
        String Minute=MinuteCMBox.getItemAt(MinuteCMBox.getSelectedIndex());
        String Hour=HourCMBox.getItemAt(HourCMBox.getSelectedIndex());
        String Meridiem=MeridiemCMBox.getItemAt(MeridiemCMBox.getSelectedIndex());
        int temp=Integer.parseInt(Hour);
        if(Meridiem.equals("P.M")){
            if(temp!=12){
                int temp2=temp+12;
                Hour=String.valueOf(temp2);
            }   
        }else{
            if(temp==12){
                Hour="0";
            }
        }
        String Time=Hour+":"+Minute;
        String Title=TitleTF.getText();
        String Discription=DiscriptionTA.getText();
        editreminder.setValue(Date, Time, CourseCode, Title, Discription);
        boolean success=editreminder.updateInfo();
        if(success==true){
            JOptionPane.showMessageDialog(rootPane, "Data Updated");
        }else{
            JOptionPane.showMessageDialog(null, "There Is something wrong");
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void setInfo(){
        con=new DBConnect().connectDB();
        setsubject();
        CourseCodeCMBox.setSelectedItem(editreminder.OldCourse);
        String[] Date=editreminder.OldDate.split("-");
        DayCMBox.setSelectedItem(Date[0]);
        MonthCMBox.setSelectedItem(Date[1]);
        YearCMBox.setSelectedItem(Date[2]);
        String[] Time=editreminder.OldTime.split(":");
        int Hour=Integer.parseInt(Time[0]);
        if(Hour>12){
            Hour=Hour-12;
            
            if(Hour<10){
              Time[0]=String.valueOf("0")+Hour;
            }
            MeridiemCMBox.setSelectedItem("P.M");
        }else{
            MeridiemCMBox.setSelectedItem("A.M");
        }
        HourCMBox.setSelectedItem(Time[0]);
        MinuteCMBox.setSelectedItem(Time[1]);
        TitleTF.setText(editreminder.Title);
        DiscriptionTA.setText(editreminder.Discription);
    }
    
    public void setsubject(){
       String User = new Temp().getUser();
       CourseCodeCMBox.removeAllItems();
        String sql = "Select * from S_SubjectInfo where Email=?" ;
            try{
                pst=con.prepareStatement(sql);
                pst.setString(1,User);
                rs = pst.executeQuery();
                while(rs.next()){
                String Subject = rs.getString("S_Code");
                 CourseCodeCMBox.addItem(Subject);
                }
            }catch (Exception ex){
                
            }
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_reminder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JComboBox<String> CourseCodeCMBox;
    private javax.swing.JComboBox<String> DayCMBox;
    private javax.swing.JTextArea DiscriptionTA;
    private javax.swing.JComboBox<String> HourCMBox;
    private javax.swing.JComboBox<String> MeridiemCMBox;
    private javax.swing.JComboBox<String> MinuteCMBox;
    private javax.swing.JComboBox<String> MonthCMBox;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField TitleTF;
    private javax.swing.JComboBox<String> YearCMBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
