
package Forms;

import Smart_Student_Backend.TaskNotificationBackEnd;
import Smart_Student_Backend.Temp;
import Smart_Student_Backend.TimeBackEnd;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


public class home_page extends javax.swing.JFrame {

    
    private String User;

    
    public home_page(String User) {
        initComponents();
        this.User=User;
        setDateTime(); 
        setNotification();
        setIconandLocation();
        
    }
    
    public home_page() {
        initComponents();
        setDateTime();
        this.User=User;
        setNotification();
        setIconandLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        AddClassRoutineBtn = new javax.swing.JLabel();
        EditClassBtn = new javax.swing.JLabel();
        ViewClassBtn = new javax.swing.JLabel();
        EditReminderBtn = new javax.swing.JLabel();
        DeleteClassBtn = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        AddReminderBtn = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        TaskLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        ViewReminderBtn = new javax.swing.JLabel();
        DeleteReminderBtn = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Student");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 170, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/rubbish-bin.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Delete");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel28.setText("Wellcome To SMART STUDENT");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 550, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 550, 80));

        AddClassRoutineBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddClassRoutineBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddClassRoutineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (1).png"))); // NOI18N
        AddClassRoutineBtn.setText(" Add");
        AddClassRoutineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddClassRoutineBtnMouseClicked(evt);
            }
        });
        jPanel3.add(AddClassRoutineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 80, -1));

        EditClassBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditClassBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditClassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (3).png"))); // NOI18N
        EditClassBtn.setText(" Edit");
        EditClassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditClassBtnMouseClicked(evt);
            }
        });
        jPanel3.add(EditClassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 460, 90, -1));

        ViewClassBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewClassBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewClassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (2).png"))); // NOI18N
        ViewClassBtn.setText(" View");
        ViewClassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewClassBtnMouseClicked(evt);
            }
        });
        jPanel3.add(ViewClassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 90, 40));

        EditReminderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditReminderBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditReminderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (3).png"))); // NOI18N
        EditReminderBtn.setText(" Edit");
        EditReminderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditReminderBtnMouseClicked(evt);
            }
        });
        jPanel3.add(EditReminderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        DeleteClassBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteClassBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteClassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (4).png"))); // NOI18N
        DeleteClassBtn.setText("Delete");
        DeleteClassBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteClassBtnMouseClicked(evt);
            }
        });
        jPanel3.add(DeleteClassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 110, -1));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel26.setText("Class Routine");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Notice :");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Monday");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        AddReminderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddReminderBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddReminderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (1).png"))); // NOI18N
        AddReminderBtn.setText(" Add");
        AddReminderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddReminderBtnMouseClicked(evt);
            }
        });
        jPanel3.add(AddReminderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        DateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setText("11-03-18");
        jPanel3.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, -1, -1));

        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel33.setText("Reminder");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        TaskLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TaskLabel.setForeground(new java.awt.Color(255, 255, 255));
        TaskLabel.setText("..........");
        jPanel3.add(TaskLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 490, -1));

        TimeLabel.setBackground(new java.awt.Color(255, 255, 255));
        TimeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        TimeLabel.setText("12.32 A.M");
        jPanel3.add(TimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        ViewReminderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewReminderBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewReminderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (2).png"))); // NOI18N
        ViewReminderBtn.setText(" View");
        ViewReminderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewReminderBtnMouseClicked(evt);
            }
        });
        jPanel3.add(ViewReminderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        DeleteReminderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteReminderBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteReminderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/1 (4).png"))); // NOI18N
        DeleteReminderBtn.setText(" Delete");
        DeleteReminderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteReminderBtnMouseClicked(evt);
            }
        });
        jPanel3.add(DeleteReminderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 510, 120, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/home123.png"))); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 590));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 100));

        jLabel31.setText("jLabel24");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 10));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void setNotification(){
        String Notification="You Have no task Today";
        TaskNotificationBackEnd task= new TaskNotificationBackEnd();
        
        task.getInfo();
        if(task.i>=0){
            Notification="You Have "+(task.i+1)+" Task Today at ";
            for(int i=0;i<=task.i;i++){
                if(task.i>0 && task.i<3){
                    Notification=Notification+",";
                    Notification=Notification+task.Time[i];
                }else{
                    Notification="You Have "+(task.i+1)+" Task Today";
                }
                
            }
            
        }
        TaskLabel.setText(Notification);
    }
    private void setDateTime(){
        String Date=new TimeBackEnd().getDate();
        DateLabel.setText(Date);
        String Time=new TimeBackEnd().getTime();
        TimeLabel.setText(Time);
    }
    private void AddClassRoutineBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddClassRoutineBtnMouseClicked
        new addclass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddClassRoutineBtnMouseClicked

    private void ViewClassBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewClassBtnMouseClicked
     new view_class().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_ViewClassBtnMouseClicked

    private void DeleteClassBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteClassBtnMouseClicked
      new delete().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_DeleteClassBtnMouseClicked

    private void EditClassBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditClassBtnMouseClicked
       new EditClass().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_EditClassBtnMouseClicked

    private void AddReminderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddReminderBtnMouseClicked
        new add_reminder().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_AddReminderBtnMouseClicked

    private void ViewReminderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewReminderBtnMouseClicked
       new reminderview().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ViewReminderBtnMouseClicked

    private void DeleteReminderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteReminderBtnMouseClicked
       new reminderdelete().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_DeleteReminderBtnMouseClicked

    private void EditReminderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditReminderBtnMouseClicked
       new reminderedit().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_EditReminderBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddClassRoutineBtn;
    private javax.swing.JLabel AddReminderBtn;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DeleteClassBtn;
    private javax.swing.JLabel DeleteReminderBtn;
    private javax.swing.JLabel EditClassBtn;
    private javax.swing.JLabel EditReminderBtn;
    private javax.swing.JLabel TaskLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel ViewClassBtn;
    private javax.swing.JLabel ViewReminderBtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
