
package Forms;

import Smart_Student_Backend.*;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.DefaultListCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class routine_byday extends javax.swing.JFrame {
    private String Day;
    private String User;
    
    
    public routine_byday(String Day) {
        initComponents();
        this.Day=Day;
        this.User=new Temp().getUser();
        setValue();
        Tabledesign();
        setIconandLocation();
        
    }
    public routine_byday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        routinetable = new javax.swing.JTable();
        daylabel = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 100));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel6.setText("Routine Information By Day");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(78, 205, 196));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        routinetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Room No", "Start Time", "End Time", "Class Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        routinetable.setGridColor(new java.awt.Color(255, 255, 255));
        routinetable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(routinetable);
        if (routinetable.getColumnModel().getColumnCount() > 0) {
            routinetable.getColumnModel().getColumn(0).setResizable(false);
            routinetable.getColumnModel().getColumn(1).setResizable(false);
            routinetable.getColumnModel().getColumn(2).setResizable(false);
            routinetable.getColumnModel().getColumn(3).setResizable(false);
            routinetable.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 330));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 720, 330));

        daylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        daylabel.setText(".......");
        jPanel1.add(daylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 140, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Day:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 810, 500));

        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Backbtn.setText("BACK");
        Backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/barckground.png"))); // NOI18N
        jLabel30.setText("jLabel30");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 580));

        setSize(new java.awt.Dimension(968, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void BackbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseClicked
      new view_class().setVisible(true);
      this.dispose();
        
    }//GEN-LAST:event_BackbtnMouseClicked

    private void Tabledesign(){
        routinetable.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer) routinetable.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        routinetable.setGridColor( Color.WHITE);
        routinetable.setForeground(Color.BLACK);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        routinetable.setOpaque(false);
        ((DefaultTableCellRenderer) routinetable.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        
    }
    private void setValue(){
        daylabel.setText(Day);
        DefaultTableModel table = (DefaultTableModel) routinetable.getModel();
        int row = table.getRowCount();
         for(int i=row-1;i>=0;i--){
             table.removeRow(i);
         }
        ViewRoutineByDayBackEnd vrbd=new ViewRoutineByDayBackEnd(User,Day);
        vrbd.getInfoFromDataBase();
        int j=vrbd.i;
        for(int i=0;i<=j;i++){
            String CourseCode=(vrbd.CourseCode[i]);
            String RoomNo=(vrbd.RoomNo[i]);
            String StartTime=(String.valueOf(vrbd.StartTime[i]));
            String EndTime=(String.valueOf(vrbd.EndTime[i]));
            String ClassType=(vrbd.ClassType[i]);
            Object[] data = {CourseCode,RoomNo,StartTime,EndTime,ClassType};
                    table.addRow(data);
        }
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(routine_byday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(routine_byday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(routine_byday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(routine_byday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new routine_byday().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backbtn;
    private javax.swing.JLabel daylabel;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable routinetable;
    // End of variables declaration//GEN-END:variables
}
