package Forms;

import Forms.home_page;
import Smart_Student_Backend.*;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class sign_in extends javax.swing.JFrame {

    
    public sign_in() {
        initComponents();
        setIconandLocation();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        PasswordTF = new javax.swing.JPasswordField();
        EmailTF = new javax.swing.JTextField();
        SignInBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        SignUpBtn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Create a new account");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 160, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 292, 210, 0));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setText("Email :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        PasswordTF.setText("jPasswordField1");
        PasswordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordTFKeyPressed(evt);
            }
        });
        jPanel1.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 210, 30));

        EmailTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EmailTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailTFKeyPressed(evt);
            }
        });
        jPanel1.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 210, 30));

        SignInBtn.setBackground(new java.awt.Color(103, 65, 114));
        SignInBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        SignInBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignInBtn.setText("Sign in");
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });
        SignInBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SignInBtnKeyPressed(evt);
            }
        });
        jPanel1.add(SignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel13.setText("PASSWORD :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        SignUpBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(103, 65, 114));
        SignUpBtn.setText("sign up");
        SignUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpBtnMouseClicked(evt);
            }
        });
        SignUpBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SignUpBtnKeyPressed(evt);
            }
        });
        jPanel1.add(SignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/user2.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/youtube.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/facebook.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/gmail.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 530, 590));

        jPanel2.setBackground(new java.awt.Color(103, 65, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel8.setText("Sign in");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Smart Student");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 210, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Join us and You can be a ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 270, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/sign1.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 440, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 585));

        setSize(new java.awt.Dimension(974, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
    LoginEvent();
      
    }//GEN-LAST:event_SignInBtnActionPerformed

    private void LoginEvent(){
        String Email =EmailTF.getText();
        String Password = String.valueOf(PasswordTF.getPassword());
        if(checkEmpty(Email,Password)==false){
            LoginBackEnd Loginbackend=new LoginBackEnd(Email,Password);
            boolean Access=Loginbackend.checkAccess();
            if(Access==true){
                JOptionPane.showMessageDialog(rootPane,"Welcome");
                new Temp().setUser(Email);
                new home_page().setVisible(true);
                this.dispose();
            }else{
                int Trails=Loginbackend.getTrail();
                JOptionPane.showMessageDialog(rootPane,"Wrong Informaiton!\n"+Trails+" trails left!");
                if(Trails==0){
                   this.dispose();
                }
            }
        }
        
    }
   
    
            
    private boolean checkEmpty(String Mail,String Pass){
        boolean Returnvariable=false;
        if(Mail.isEmpty()){
             JOptionPane.showMessageDialog(rootPane,"Email Is Empty");
            Returnvariable=true;
        }else if(Pass.isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Password Is Empty");
            Returnvariable=true;
        }
        return Returnvariable;
    }
    
    private void SignInBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SignInBtnKeyPressed
        if(evt.getKeyCode()==10){
            LoginEvent();
        }
    }//GEN-LAST:event_SignInBtnKeyPressed

    private void PasswordTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTFKeyPressed
        if(evt.getKeyCode()==10){
            LoginEvent();
        }
    }//GEN-LAST:event_PasswordTFKeyPressed

    private void EmailTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTFKeyPressed
        if(evt.getKeyCode()==10){
            LoginEvent();
        }
    }//GEN-LAST:event_EmailTFKeyPressed

    private void SignUpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpBtnMouseClicked
        signUp(10);
    }//GEN-LAST:event_SignUpBtnMouseClicked

    private void SignUpBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SignUpBtnKeyPressed
        signUp(evt.getKeyCode());
    }//GEN-LAST:event_SignUpBtnKeyPressed

    private void signUp(int KeyValue){
        if(KeyValue==10){
            
            new sign_up().setVisible(true);
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTF;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JLabel SignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
