/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Forms.sign_in;
import Smart_Student_Backend.DataVerify;
import Smart_Student_Backend.SignUpBackEnd;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class sign_up extends javax.swing.JFrame {

    public sign_up() {
        initComponents();
        setIconandLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PasswordTF = new javax.swing.JPasswordField();
        EmailTF = new javax.swing.JTextField();
        SignUpBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        SignInbtn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PhoneTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Task Related Subject :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 230, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Already have an account");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 160, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 292, 210, 0));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setText("NAME :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setText("EMAIL :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        PasswordTF.setText("jPasswordField1");
        jPanel1.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 210, 30));

        EmailTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(EmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 210, 30));

        SignUpBtn.setBackground(new java.awt.Color(103, 65, 114));
        SignUpBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtn.setText(" Get Started");
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel13.setText("PASSWORD :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        NameTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(NameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 210, 30));

        SignInbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        SignInbtn.setForeground(new java.awt.Color(103, 65, 114));
        SignInbtn.setText("sign in");
        SignInbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInbtnMouseClicked(evt);
            }
        });
        jPanel1.add(SignInbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/gmail.png"))); // NOI18N
        jLabel14.setText("gmail");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel14MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/youtube.png"))); // NOI18N
        jLabel15.setText("Youtube");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/facebook.png"))); // NOI18N
        jLabel16.setText("facebook");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel16MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        PhoneTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(PhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, 30));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel17.setText("Phone :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 520, 580));

        jPanel2.setBackground(new java.awt.Color(103, 65, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel8.setText("Sign Up");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BACK");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Smart Student");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 210, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Join us and You can be a ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 270, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/sign1.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 440, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 585));

        setSize(new java.awt.Dimension(968, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        signUp();
        
    }//GEN-LAST:event_SignUpBtnActionPerformed

    private void SignInbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInbtnMouseClicked
       new sign_in().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_SignInbtnMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
       
    try {
    String URL ="https://www.youtube.com/";
    java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

    }   catch (IOException ex) {    
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }  
    catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e.getMessage());
            }     
               
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased
        try {
    String URL ="https://accounts.google.com/SignUp?hl=en-GB";
    java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

    }   catch (IOException ex) {    
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }  
    catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_jLabel14MouseReleased

    private void jLabel16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseReleased
       try {
    String URL ="https://www.facebook.com/";
    java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

    }   catch (IOException ex) {    
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
        }  
    catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_jLabel16MouseReleased

    
    private void signUp(){
        String Name = NameTF.getText();
        String Phone = PhoneTF.getText();
        String Email=EmailTF.getText();
        String Password=String.valueOf(PasswordTF.getPassword());
        if(Name.isEmpty() || Email.isEmpty() || Password.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please Input All Information");
        }else{
            DataVerify verify= new DataVerify();
            if(verify.checkName(Name) &&  verify.checkEmail(Email) && verify.checkPassword(Password)){
                SignUpBackEnd signupbackend=new SignUpBackEnd(Name,Email,Phone,Password);
                boolean Success=signupbackend.run();
                if(Success==true){
                 JOptionPane.showMessageDialog(rootPane, Name+",\nYou are now part of Smart Student\nHope will Enjoy!!!");
                 new sign_in().setVisible(true);
                 this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No Information Saved");
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JLabel SignInbtn;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
