
package Forms;

import Forms.home_page;
import Smart_Student_Backend.DBConnect;
import Smart_Student_Backend.Temp;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class view_class extends javax.swing.JFrame {
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;

    public view_class() {
        initComponents();
        con=new DBConnect().connectDB();
        setsubject();
        setIconandLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        SubjectCMBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ViewSubjectBtn = new javax.swing.JButton();
        ViewRoutineBtn = new javax.swing.JButton();
        DayCMBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SubjectRadio = new javax.swing.JRadioButton();
        DayRadio = new javax.swing.JRadioButton();
        BackBtn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, -1, -1));

        SubjectCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(SubjectCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 100));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject Code :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel6.setText("View Routine");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(78, 205, 196));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewSubjectBtn.setBackground(new java.awt.Color(232, 126, 4));
        ViewSubjectBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewSubjectBtn.setText("View Subject Information");
        ViewSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSubjectBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ViewSubjectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 147, -1, -1));

        ViewRoutineBtn.setBackground(new java.awt.Color(52, 73, 94));
        ViewRoutineBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewRoutineBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewRoutineBtn.setText("View Routine");
        ViewRoutineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRoutineBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ViewRoutineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 196, -1, -1));

        DayCMBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DayCMBox.setMaximumRowCount(12);
        DayCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Friday", "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday" }));
        DayCMBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayCMBoxActionPerformed(evt);
            }
        });
        jPanel2.add(DayCMBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 60, 130, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search By   :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 100, 120, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Day :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 61, 70, -1));

        SearchGroup.add(SubjectRadio);
        SubjectRadio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubjectRadio.setText("Subject Code");
        jPanel2.add(SubjectRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 98, -1, -1));

        SearchGroup.add(DayRadio);
        DayRadio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DayRadio.setText("Day");
        jPanel2.add(DayRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 98, 102, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 650, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 690, 400));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/barckground.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        setSize(new java.awt.Dimension(970, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    
    public void setsubject(){
        
       String User = new Temp().getUser();
        String sql = "Select * from S_SubjectInfo where Email=?" ;
            try{
                pst=con.prepareStatement(sql);
                pst.setString(1,User);
                rs = pst.executeQuery();
                while(rs.next()){
                String Subject = rs.getString("S_Code");
                 SubjectCMBox.addItem(Subject);
                }
            }catch (Exception ex){
                
            }
    }
    
    private void DayCMBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayCMBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayCMBoxActionPerformed

    private void ViewRoutineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRoutineBtnActionPerformed
        if(DayRadio.isSelected()){
            String Day=DayCMBox.getItemAt(DayCMBox.getSelectedIndex());
            new routine_byday(Day).setVisible(true);
            this.dispose();
        }else if(SubjectRadio.isSelected()){
            String CourseCode=SubjectCMBox.getItemAt(SubjectCMBox.getSelectedIndex());
            new info_subject(CourseCode).setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Search By is not selected");
        }
        
    }//GEN-LAST:event_ViewRoutineBtnActionPerformed

    private void ViewSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSubjectBtnActionPerformed
        if(SubjectRadio.isSelected()){
            String CourseCode=SubjectCMBox.getItemAt(SubjectCMBox.getSelectedIndex());
            new view_subject_info(CourseCode).setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please Seletect Search By Subject Code");
        }
    }//GEN-LAST:event_ViewSubjectBtnActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
     new home_page().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_class().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JComboBox<String> DayCMBox;
    private javax.swing.JRadioButton DayRadio;
    private javax.swing.ButtonGroup SearchGroup;
    private javax.swing.JComboBox<String> SubjectCMBox;
    private javax.swing.JRadioButton SubjectRadio;
    private javax.swing.JButton ViewRoutineBtn;
    private javax.swing.JButton ViewSubjectBtn;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
