
package Forms;

import Smart_Student_Backend.ViewSubjectInfoBackEnd;
import java.awt.Toolkit;

public class view_subject_info extends javax.swing.JFrame {
    private String CourseCode;
    
    public view_subject_info(String CourseCode){
        initComponents();
        this.CourseCode=CourseCode;
        setInfo();
        setIconandLocation();
    }
    public view_subject_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        SUbjectNameLabel = new javax.swing.JLabel();
        TeacherNameLabel = new javax.swing.JLabel();
        TeacherPhoneLabel = new javax.swing.JLabel();
        TeacherMailLabel = new javax.swing.JLabel();
        CreditLabel = new javax.swing.JLabel();
        DurationLabel = new javax.swing.JLabel();
        CourseCodeLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("View Subject information");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 420, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cradit :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Duration :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Teacher Name  :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Subject Name   :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Teacher Mail    :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Teacher Phone :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Subject Code    :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        BackBtn.setBackground(new java.awt.Color(225, 190, 88));
        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        SUbjectNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SUbjectNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        SUbjectNameLabel.setText("jLabel2");
        getContentPane().add(SUbjectNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 250, 30));

        TeacherNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeacherNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        TeacherNameLabel.setText("jLabel2");
        getContentPane().add(TeacherNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 230, 30));

        TeacherPhoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeacherPhoneLabel.setForeground(new java.awt.Color(204, 204, 204));
        TeacherPhoneLabel.setText("jLabel2");
        getContentPane().add(TeacherPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 230, 30));

        TeacherMailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeacherMailLabel.setForeground(new java.awt.Color(204, 204, 204));
        TeacherMailLabel.setText("jLabel2");
        getContentPane().add(TeacherMailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 240, 30));

        CreditLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreditLabel.setForeground(new java.awt.Color(204, 204, 204));
        CreditLabel.setText("jLabel2");
        getContentPane().add(CreditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 50, 40));

        DurationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DurationLabel.setForeground(new java.awt.Color(204, 204, 204));
        DurationLabel.setText("jLabel2");
        getContentPane().add(DurationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 60, 40));

        CourseCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CourseCodeLabel.setForeground(new java.awt.Color(204, 204, 204));
        CourseCodeLabel.setText("jLabel2");
        getContentPane().add(CourseCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 240, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/addroutine.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smart_student/smar1t.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 230, 570));

        setSize(new java.awt.Dimension(969, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconandLocation(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("std.png")));
        setLocationRelativeTo(null);
    }
    public void setInfo(){
        ViewSubjectInfoBackEnd viewsubject = new ViewSubjectInfoBackEnd(CourseCode);
        viewsubject.getInfoFromDataBase();
        CourseCodeLabel.setText(CourseCode);
        SUbjectNameLabel.setText(viewsubject.CourseName);
        CreditLabel.setText(String.valueOf(viewsubject.CourseCredit));
        TeacherNameLabel.setText(viewsubject.CourseTeacher);
        TeacherMailLabel.setText(viewsubject.TeacherEmail);
        TeacherPhoneLabel.setText(viewsubject.TecherPhone);
        DurationLabel.setText(String.valueOf(viewsubject.Duration));
        
    }
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
      new view_class().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_subject_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_subject_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel CourseCodeLabel;
    private javax.swing.JLabel CreditLabel;
    private javax.swing.JLabel DurationLabel;
    private javax.swing.JLabel SUbjectNameLabel;
    private javax.swing.JLabel TeacherMailLabel;
    private javax.swing.JLabel TeacherNameLabel;
    private javax.swing.JLabel TeacherPhoneLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
